# Generated by Django 4.2.1 on 2023-05-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
