# Generated by Django 4.2.1 on 2023-05-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
